alter table STATISTICSPROJECTRC_IMPORT_LOG add constraint FK_STATISTICSPROJECTRC_IMPORT_LOG_ON_FILE foreign key (FILE_ID) references SYS_FILE(ID);
create index IDX_STATISTICSPROJECTRC_IMPORT_LOG_ON_FILE on STATISTICSPROJECTRC_IMPORT_LOG (FILE_ID);
